apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  DB_POSTGRESDB_USER: {your_username} # get it from azure portal and convert it into base64 and then put here.
  DB_POSTGRESDB_PASSWORD: (your_password} # Create a password it you havnt created before OR get it from azure portal and convert it into base64 and then put here.
